### ISSUE TITLE
CONNECT TO LB!!! undefined

### ISSUE THREAD

**Issue by vaibhavch** [cracker0dks/Accelerator#23]
CONNECT TO LB!!! undefined

<img width="814" alt="Screenshot 2020-08-01 at 4 24 13 PM" src="https://user-images.githubusercontent.com/1785310/89100282-8475c800-d413-11ea-83a6-62701b235d70.png">

I have setup separate turn server too. hosted on a domain with https. all socket ports are allowed. It was perfectly working for a while (all features). Now I stuck on this thing. Could you enlighten me on what went wrong ?

**Comment by cracker0dks** [comment]
do you have any server erros. On the server there is also running the Loadbalancer (LB), it seems that it crashed / ended? Can you please post an error log, then try to restart the server to get it back to working. If you are using docker try:
`docker logs acc --tail 1000` for the logs and
`docker restart acc` to restart the server.

**Comment by vaibhavch** [comment]
I solved it by running puppeteer. thanks.
