### ISSUE TITLE
PLs tell how did you make it 

### ISSUE THREAD

**Issue by Parth308** [cracker0dks/Accelerator#24]
PLs tell in a video full tuorial pls

**Comment by cracker0dks** [comment]
don't know what you really mean by that. What part do you need a better explanation for?

**Comment by Parth308** [comment]
Actually i am not able to install it on localhost

**Comment by cracker0dks** [comment]
We have an installation guid here: https://github.com/cracker0dks/Accelerator#installation-without-docker 
Without any error logs or problem descreptions I can not really help you.
