### ISSUE TITLE
Can not join the rooms

### ISSUE THREAD

**Issue by CptSilent** [cracker0dks/Accelerator#38]
I'm running in windows 2k12 server with nodejs
Everything is working well i have configured security and firewall issues, When click on room it won't connect,
On console
![image](https://user-images.githubusercontent.com/46040354/100178923-e8b31f00-2f0f-11eb-8b03-4b61610348c7.png)

**Comment by cracker0dks** [comment]
This is most likely a connection problem. Check if on the server side webRTC port: 5004 UDP is open. Maybe open 5000-5100 to be save (don't know if only 5004 is used for establishing the connection).

On the long run you will also need a TURN Server for clients with double NAT or other restrictive firewall conditions. But be sure your server is working without the TURN for "normal" clients so TURN is not always needed.

**Comment by CptSilent** [comment]
I found the problem
TCP 19302 must be open at windows server and firewall
stun.l.google.com:19302
