### ISSUE TITLE
what sfu we use？

### ISSUE THREAD

**Issue by qbgit** [cracker0dks/Accelerator#40]
I do not understand what sfu server we use ? like janus or other sfu server

**Comment by cracker0dks** [comment]
we build our own sfu. It is using the chromium stack, for webRTC features, and is running inside puppeteer. Note that this is a Audio MCU and Video SFU.
The code: https://github.com/cracker0dks/Accelerator/tree/master/public/ezMCU
The "index.html" is called inside puppeteer (with the correct parameters) here: https://github.com/cracker0dks/Accelerator/blob/master/acc_server_modules/ezMCU/s_ezMCUsignaling.js#L345

**Comment by qianbo0423** [comment]
ok,i get you
