### ISSUE TITLE
navigator.getUserMedia is not a function

### ISSUE THREAD

**Issue by narendraraghuwanshi** [cracker0dks/Accelerator#42]
I install the below code on AWS lightsail and start with node
server started and I got this error [](url)
![image](https://user-images.githubusercontent.com/26792935/109027919-4a3d8200-76e7-11eb-83cd-9801444f22ca.png)

**Comment by cracker0dks** [comment]
This seems to be a client problem. You sure you are using a working browser like: chrome, firefox, (new) Edge?

**Comment by hthetiot** [comment]
It's most likely the page is not over https, chrome does not expose getUserMedia unless https or localhost. 

Note: this issue report is light, @narendraraghuwanshi could have reported at least the browser, version and hostname.

**Comment by cracker0dks** [comment]
@hthetiot ahh, you are right, not thought about the http thing, that's probably it!
