### ISSUE TITLE
Force Machine IP Address as Host

### ISSUE THREAD

**Issue by GerryGit** [cracker0dks/Accelerator#50]
I would like to run Accelerator on a local network using the host machine IP: 192.16.1..xxx as the url instead of 127.0.0.1. I have tried to do this by changing urls in various parts of the code. However when the landing page asking for username  served, the microphone and camera popup is not served. The behavior is the same for unmodified code. Is it possible to expose the system on a local network without an external server? Application works perfectly on one machine with two separate browsers on 127.0.0.1.

**Comment by cracker0dks** [comment]
I think browsers do not allow Audio, Video, Screen share without https. So you need to setup a cert, then this should work.
